CREATE OR REPLACE PROCEDURE COMISION_EMPLEADO(A IN EMPLEADOS.CODIGOEMPLEADO%TYPE, B IN NUMBER) AS
REGEMP EMPLEADOS%ROWTYPE;
TVEmpleado NUMBER;
BEGIN
SELECT * INTO REGEMP FROM EMPLEADOS WHERE CODIGOEMPLEADO=A;
SELECT SUM(Cantidad*PrecioUnidad) INTO TVEmpleado FROM DetallePedidos NATURAL JOIN Pedidos NATURAL JOIN Clientes
				 WHERE CODIGOEMPLEADOREPVENTAS=A;
DBMS_OUTPUT.PUT_LINE(REGEMP.NOMBRE||' '||REGEMP.APELLIDO1||' '||REGEMP.APELLIDO2||' VENTAS: '||TVEmpleado||' Comision: '||(COMISION(TVEmpleado,B)));
END;
/
