CREATE OR REPLACE PROCEDURE PAGOS_CLIENTE(A IN CLIENTES.CODIGOCLIENTE%TYPE) AS
REG_CLI CLIENTES%ROWTYPE;
TOTAL NUMBER:=0;
CURSOR PAG_CLI IS SELECT * FROM PAGOS WHERE CODIGOCLIENTE=A ;
BEGIN
SELECT * INTO REG_CLI FROM CLIENTES WHERE CODIGOCLIENTE=A;
-- IMPRIMIMOS LOS DATOS DEL CLIENTE
DBMS_OUTPUT.PUT_LINE('CODIGO CLIENTE: '||REG_CLI.CODIGOCLIENTE);
DBMS_OUTPUT.PUT_LINE('NOMBRE CLIENTE: '||REG_CLI.NOMBRECLIENTE);
DBMS_OUTPUT.PUT_LINE('CIUDAD CLIENTE: '||REG_CLI.CIUDAD);
DBMS_OUTPUT.PUT_LINE('PAIS   CLIENTE: '||REG_CLI.PAIS);
DBMS_OUTPUT.PUT_LINE('=============================================');
-- IMPRIMIMOS LOS DETALLES DEL PAGO

	DBMS_OUTPUT.PUT_LINE('ID-TRANSACCION  FECHA      FORMA  CANTIDAD');
	DBMS_OUTPUT.PUT_LINE('=============================================');
FOR REG_PAG IN PAG_CLI LOOP
	DBMS_OUTPUT.PUT_LINE(REG_PAG.IDTRANSACCION||'   '||REG_PAG.FECHAPAGO||'   '||REG_PAG.FORMAPAGO||' '||REG_PAG.CANTIDAD);
	TOTAL:=TOTAL+REG_PAG.CANTIDAD;
END LOOP;
	DBMS_OUTPUT.PUT_LINE('=============================================');
DBMS_OUTPUT.PUT_LINE('TOTAL PAGOS EFECTUADOS: '||TOTAL); 
END;
/
