CREATE DATABASE CONCESIONARIO;
USE CONCESIONARIO;

CREATE TABLE CLIENTE (
	COD_INTERNO 	INT UNSIGNED PRIMARY KEY,
	NIF 		VARCHAR (10) NOT NULL,
	NOMBRE		VARCHAR (40) NOT NULL,
	DIRECCION 	VARCHAR (25) NOT NULL,
	CIUDAD		VARCHAR (30) NOT NULL,
	TELEFONO	SMALLINT UNSIGNED NOT NULL
) ENGINE=INODB;

CREATE TABLE COCHE (
	MATRICULA	VARCHAR (15) PRIMARY KEY,
	MARCA		VARCHAR (15) NOT NULL,
	MODELO		VARCHAR (20) NOT NULL,
	COLOR		VARCHAR (15) NOT NULL,
	PRECIO_VENTA	INT NOT NULL,
	COD_INTERNO 	INT UNSIGNED REFERENCES CLIENTE(COD_INTERNO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INODB;

CREATE TABLE REVISION (
	CODIGO		INT UNSIGNED PRIMARY KEY,
	FECHA		DATE NOT NULL,
	TIPO_CAMBIO	VARCHAR (20) NOT NULL,
	MATRICULA 	INT UNSIGNED REFERENCES COCHE(MATRICULA) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INODB;
