-- Muestra la calificación, Lo que ponemos en Begin es para que nos pida en pantalla introducirla

SET SERVEROUTPUT ON;
DECLARE
NOTA INT;

BEGIN
NOTA:=&NOTA;
CASE
WHEN (NOTA >=1) AND (NOTA <5) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES INSUFICIENTE '||NOTA);
WHEN (NOTA >=5) AND (NOTA<6) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES SUFICIENTE '||NOTA);
WHEN (NOTA >=6) AND (NOTA<7) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES BIEN '||NOTA);
WHEN (NOTA >=6) AND (NOTA<9) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES NOTABLE '||NOTA);
WHEN (NOTA >=8) AND (NOTA<9) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES SOBRESALIENTE '||NOTA);
WHEN (NOTA >=9) AND (NOTA<10) THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES MATRICULA '||NOTA);
ELSE
	DBMS_OUTPUT.PUT_LINE ('LA NOTA INTRODUCIDA NO ES VALIDA '||NOTA);
END CASE;

END;
/
