-- Muestra la calificación, Lo que ponemos en Begin es para que nos pida en pantalla introducirla

SET SERVEROUTPUT ON;
DECLARE
NOTA INT;

BEGIN
NOTA:=&NOTA;
CASE NOTA
WHEN 1 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES INSUFICIENTE '||NOTA);
WHEN 2 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES INSUFICIENTE '||NOTA);
WHEN 3 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES INSUFICIENTE '||NOTA);
WHEN 4 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES INSUFICIENTE '||NOTA);

WHEN 5 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES SUFICIENTE '||NOTA);
WHEN 6 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES BIEN '||NOTA);
WHEN 7 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES NOTABLE '||NOTA);
WHEN 8 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES NOTABLE '||NOTA);
WHEN 9 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES SOBRESALIENTE '||NOTA);
WHEN 10 THEN
	DBMS_OUTPUT.PUT_LINE ('LA NOTA ES MATRICULA '||NOTA);

ELSE
	DBMS_OUTPUT.PUT_LINE ('LA NOTA INTRODUCIDA NO ES VALIDA '||NOTA);
END CASE;

END;
/
