-- Creamos una funcion que nos calcula el area de 1 triangulo
CREATE OR REPLACE FUNCTION AREATRIANGULO(BASE IN FLOAT,ALTURA IN FLOAT) RETURN FLOAT
IS
AREA FLOAT;
BEGIN
	AREA:=(BASE*ALTURA/2);
	RETURN AREA;
END;
/
