SET SERVEROUTPUT ON
DECLARE
NUM INT;
A INT:=30;
B INT:=15;
BEGIN
DBMS_OUTPUT.PUT_LINE('EL PRIMER VALOR ES '||A);
DBMS_OUTPUT.PUT_LINE('EL SEGUNDO VALOR ES '||B);
NUM:=A+B;
DBMS_OUTPUT.PUT_LINE('LA SUMA DE AMBOS ES '||NUM);
NUM:=A-B;
DBMS_OUTPUT.PUT_LINE('LA RESTA DE AMBOS ES '||NUM);
NUM:=A*B;
DBMS_OUTPUT.PUT_LINE('LA MULTIPLICACION DE AMBOS ES '||NUM);
NUM:=A/B;
DBMS_OUTPUT.PUT_LINE('LA DIVISION DE AMBOS ES '||NUM);
END;
/
