-- Imprime los 100 primeros numeros no funciona el for
SET SERVEROUTPUT ON

DECLARE
NOTA INT:=0;

BEGIN
DBMS_OUTPUT.PUT_LINE('Bucle con loop');
LOOP
NOTA:=NOTA+1;
IF (NOTA<=100) THEN
	DBMS_OUTPUT.PUT_LINE(NOTA);
END IF;
EXIT WHEN (NOTA>100);
END LOOP;

DBMS_OUTPUT.PUT_LINE('Bucle con while');
NOTA:=1;
WHILE NOTA<=100 LOOP
	DBMS_OUTPUT.PUT_LINE(NOTA);
	NOTA:=NOTA+1;
END LOOP;

DBMS_OUTPUT.PUT_LINE('Bucle con for');
NOTA:=1;
FOR NOTA IN 1 .. 100 LOOP
	DBMS_OUTPUT.PUT_LINE(NOTA);
END LOOP;

END;
/

