SET SERVEROUTPUT ON
DECLARE
num INT;
A INT:=5;
B INT:=5;
BEGIN
 --NUM:=0;
 DBMS_OUTPUT.PUT_LINE(' EL VALOR DE NUM ES:'||NUM);
 NUM:=NUM+5;
 DBMS_OUTPUT.PUT_LINE(' EL VALOR DE NUM ES:'||NUM);
 NUM:=NUM+5;
 DBMS_OUTPUT.PUT_LINE(' EL VALOR DE NUM ES:'||NUM);
END;
/
