SET SERVEROUTPUT ON
DECLARE
num INT;
A INT:=5;
B INT:=4;
BEGIN
IF A > B THEN
 	DBMS_OUTPUT.PUT_LINE(' EL MAYOR ES A QUE VALE:'||A);
ELSE
 	DBMS_OUTPUT.PUT_LINE(' A NO ES EL MAYOR, Y VALE:'||A);
END IF;
END;
/
