SET SERVEROUTPUT ON
DECLARE
num INT;
A INT:=5;
B INT:=5;
BEGIN
IF A > B THEN
 	DBMS_OUTPUT.PUT_LINE(' EL MAYOR ES A QUE VALE:'||A);
ELSIF B > A THEN
 	DBMS_OUTPUT.PUT_LINE(' EL MAYOR ES B, Y VALE:'||B);
ELSE
	 DBMS_OUTPUT.PUT_LINE(' SON IGUALES Y VALEN:'||A);
END IF;
END;
/
