SET SERVEROUTPUT ON
-- NUESTRA LOS NUMEROS PRIMOS MENORES QUE CIEN
DECLARE
FACTORIAL INT:=1;

BEGIN
FOR I IN 1 .. 200 LOOP
	FACTORIAL:=1;
	FOR J IN 1.. I LOOP
		FACTORIAL:=FACTORIAL*J;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(I||'!='||FACTORIAL);
END LOOP;

END;
/
