CREATE OR REPLACE FUNCTION ESPRIMO(N IN INT) RETURN BOOLEAN
IS
PRIMO BOOLEAN;
I INTEGER;
BEGIN
	PRIMO:=TRUE;
	I:=2;
	WHILE (i<= N/2 AND PRIMO) LOOP
		IF MOD(N,I)=0 THEN
			PRIMO:=FALSE;
		END IF;
		I:=I+1;
	END  LOOP;
	RETURN PRIMO;
END;
/
