SET SERVEROUTPUT ON
DECLARE
N1 INT := 21;
N2 INT := 5;
C INT;
RESTO INT;
BEGIN
C:=DIVIDIR(21,5,RESTO);
DBMS_OUTPUT.PUT_LINE('DIVIDENDO: '||N1||' DIVISOR: '||N2||' COCIENTE :'||C||' RESTO: '||RESTO);
END;
/
