CREATE OR REPLACE PROCEDURE LISTAPRIMOS(N IN INT) 
AS
	NPRIMOS INT :=0;
	I INT :=1;
BEGIN
	WHILE 
NPRIMOS < N LOOP
		IF ESPRIMO(I) THEN
			DBMS_OUTPUT.PUT_LINE(I);
			NPRIMOS:=NPRIMOS+1;
		END IF;
		I:=I+1;
	END LOOP;
END;
/
