-- CREAR UN PROCEDIMIENTO QUE  AUMENTE EL LIMITE DE CREDITO A TODOS AQUELLOS CLIENTES Q A DIA DE HOY TENGAN SALDO NEGATIVO
CREATE OR REPLACE PROCEDURE AUMENTACREDITO AS
TOTALPAGADO NUMBER;
TOTALFACTURADO NUMBER;
CURSOR Cli IS SELECT CODIGOCLIENTE,LIMITECREDITO FROM CLIENTES;

BEGIN

FOR RegCli IN Cli LOOP
	SELECT SUM(CANTIDAD) INTO TOTALPAGADO FROM PAGOS WHERE CODIGOCLIENTE=RegCli.CODIGOCLIENTE;
	SELECT SUM(PrecioUnidad*Cantidad) INTO TotalFacturado FROM DetallePedidos Natural Join Pedidos where CodigoCliente=RegCli.CODIGOCLIENTE;
	-- ES MUY UTIL EL USO DE LA FUNCIÓN NVL PARA EVITAR VALORES NULOS NVL(E1,E2), EN CASO DE QUE LA E1 VALGA NULO USA LA E2
	IF NVL(TOTALFACTURADO,0)>NVL(TOTALPAGADO,0) THEN
		DBMS_OUTPUT.PUT_LINE(REGCli.CODIGOCLIENTE||' TOTAL FACTURADO: '||TOTALFACTURADO||' TOTAL PAGADO: '||TOTALPAGADO);		
		UPDATE CLIENTES SET LIMITECREDITO=INCREMENTA(20,LIMITECREDITO) WHERE CODIGOCLIENTE=RegCli.CODIGOCLIENTE;
	END IF;
END LOOP;

END;
/
