-- CREAR UN PROCEDIMIENTO QUE ACTUALICE EL SALDO DE LOS CLIENTES
CREATE OR REPLACE PROCEDURE ACTUALIZASALDO AS
TOTALPAGADO NUMBER;
TOTALFACTURADO NUMBER;
TotalSaldo NUMBER;
CURSOR Cli IS SELECT CODIGOCLIENTE,LIMITECREDITO FROM CLIENTES;

BEGIN

FOR RegCli IN Cli LOOP
	SELECT SUM(CANTIDAD) INTO TOTALPAGADO FROM PAGOS WHERE CODIGOCLIENTE=RegCli.CODIGOCLIENTE;
	SELECT SUM(PrecioUnidad*Cantidad) INTO TotalFacturado FROM DetallePedidos 
	Natural Join Pedidos where CodigoCliente=RegCli.CODIGOCLIENTE;
	-- ES MUY UTIL EL USO DE LA FUNCIÓN NVL PARA EVITAR VALORES NULOS NVL(E1,E2)
	-- EN CASO DE QUE LA E1 VALGA NULO USA
	TotalSaldo:= NVL(TOTALPAGADO,0)-NVL(TOTALFACTURADO,0);
	UPDATE CLIENTES SET SALDO=TotalSaldo WHERE CODIGOCLIENTE=RegCli.CODIGOCLIENTE;
END LOOP;

END;
/
