SET SERVEROUTPUT ON
DECLARE
NUM1 INT:=0;
NUM2 INT:=0;
SIGNO VARCHAR(2);
RESULTADO INT:=0;
SEGUIR VARCHAR(2);
BEGIN

LOOP
NUM1:=&EL_PRIMER_NUMERO;
NUM2:=&EL_SEGUNDO_NUMERO;
DBMS_OUTPUT.PUT_LINE ('OPERACIONES POSIBLES +(SUMA), -(RESTA), *(MULTIPLICACION), /(DIVISION) Y **(POTENCIA)');
SIGNO:=&OPERACION;
RESULTADO:=NUM1||SIGNO||NUM2
DBMS_OUTPUT.PUT_LINE ('EL RESULTADO ES '||RESULTADO);
DBMS_OUTPUT.PUT_LINE ('QUIERES CONTINUAR');
SEGUIR:=&CONTINUAR;
EXIT WHEN SEGUIR=SI;
END LOOP;

END;
/
