SET SERVEROUTPUT ON
DECLARE
NOTA NUMERIC(4,2):=2.8;
BEGIN
IF NOTA > 0 AND NOTA <5 THEN
 	DBMS_OUTPUT.PUT_LINE( NOTA||' ES INSUFICIENTE');
ELSIF NOTA >=5 AND NOTA < 6 THEN
	DBMS_OUTPUT.PUT_LINE( NOTA||' ES SUFICIENTE');
ELSIF NOTA >=6 AND NOTA < 7 THEN
	DBMS_OUTPUT.PUT_LINE( NOTA||' ES BIEN');
ELSIF NOTA >=7 AND NOTA < 8.5 THEN
	DBMS_OUTPUT.PUT_LINE( NOTA||' ES NOTABLE');
ELSIF NOTA >=8.5 AND NOTA < 10 THEN
	DBMS_OUTPUT.PUT_LINE( NOTA||' ES SOBRESALIENTE');
ELSE
 	DBMS_OUTPUT.PUT_LINE(NOTA||' NO ES UNA NOTA CORRECTA');
END IF;
END;
/
