CREATE OR REPLACE PROCEDURE P_PRIMO(NUM IN INTEGER)
IS
PRIMO INT:=0;
ES boolean;
PRIMOS VARCHAR(255);
BEGIN
PRIMO:=NUM-1;
ES:=true;

WHILE PRIMO>1 LOOP
	IF MOD(NUM,PRIMO)=0 THEN
	ES:=false;
	PRIMOS:=PRIMOS||' '||PRIMO;
	END IF;
	PRIMO:=PRIMO-1;
END LOOP;

IF ES=false THEN
DBMS_OUTPUT.PUT_LINE ('EL NUMERO NO ES PRIMO Y SUS DIVISORES SON'||PRIMOS);
ELSE
DBMS_OUTPUT.PUT_LINE ('EL NUMERO ES PRIMO');
END IF;
END;
/
