CREATE OR REPLACE PROCEDURE EstadoCliente(nCliente IN Clientes.codigoCliente%TYPE) AS

rCliente Clientes%ROWTYPE;
TOTAL INTEGER;
PAGADO INTEGER;
RESTA INTEGER;
BEGIN 
Select * into rCliente from Clientes where CodigoCliente=nCliente;
	DBMS_OUTPUT.PUT_LINE('Nombre: '||rCliente.NombreCliente);
	DBMS_OUTPUT.PUT_LINE('Ciudad: '||rCliente.Ciudad);
	DBMS_OUTPUT.PUT_LINE('Pais: '||rCliente.Pais); 

SELECT SUM(CANTIDAD*PRECIOUNIDAD)INTO TOTAL FROM PEDIDOS NATURAL JOIN DETALLEPEDIDOS WHERE CODIGOCLIENTE=nCliente;
SELECT SUM(CANTIDAD) INTO PAGADO FROM PAGOS WHERE CodigoCliente=nCliente;
RESTA:=TOTAL-PAGADO;
DBMS_OUTPUT.PUT_LINE('EL TOTAL FACTURADO ES: '||TOTAL);
DBMS_OUTPUT.PUT_LINE('EL TOTAL PAGADO ES: '||PAGADO);
DBMS_OUTPUT.PUT_LINE('RESTA POR PAGAR: '|| RESTA);

END;
/

