-- solucioens ejercicio 1
-- a
CREATE TABLE jugcopia AS SELECT * FROM jugadores;
INSERT INTO JUGCOPIA VALUES (500,'Ricky Rubio','Spain','6-4',200,'C','Timberwolves');

-- b
DELETE FROM JUGCOPIA WHERE EQUIPO IN SELECT NOMBRE FROM EQUIPOS WHERE CONFERENCIA='East';

-- o también
DELETE FROM JUGCOPIA WHERE EXISTS (SELECT NOMBRE FROM EQUIPOS WHERE JUGCOPIA.NOMBRE_EQUIPO=EQUIPOS.NOMBRE AND CONFERENCIA='East' );


-- c
UPDATE JUGCOPIA SET PROCEDENCIA='España' WHERE PROCEDENCIA='Spain';
