--Realiza un procedimiento que MUESTRE LOS DETALLES DE UN PEDIDO
CREATE OR REPLACE PROCEDURE MUESTRAPEDIDO(CP IN PEDIDOS.CODIGOPEDIDO%TYPE) AS
	REGCLI CLIENTES%ROWTYPE;
	TOTALP NUMBER;
	FECHAP PEDIDOS.FECHAPEDIDO%TYPE;
	CURSOR DP IS SELECT CODIGOPRODUCTO,PRECIOUNIDAD,CANTIDAD,NOMBRE FROM DETALLEPEDIDOS 
	NATURAL JOIN PRODUCTOS WHERE CODIGOPEDIDO=CP;
BEGIN
	-- MOSTRAMOS LOS DATOS DE CABECERA DEL PEDIDO REFERENTE AL CLIENTE SOBRE ESE PEDIDO.
	SELECT * INTO REGCLI FROM CLIENTES WHERE CODIGOCLIENTE=(SELECT CODIGOCLIENTE FROM PEDIDOS WHERE CODIGOPEDIDO=CP);
	DBMS_OUTPUT.PUT_LINE('PEDIDO Nº:        '||CP);
	DBMS_OUTPUT.PUT_LINE('CLIENTE:          '||REGCLI.NOMBRECLIENTE);
	DBMS_OUTPUT.PUT_LINE('DIRECCIÓN:        '||REGCLI.LINEADIRECCION1||' '||REGCLI.LINEADIRECCION2);
	DBMS_OUTPUT.PUT_LINE('CIUDAD:           '||REGCLI.CIUDAD);
	DBMS_OUTPUT.PUT_LINE('PAIS:             '||REGCLI.PAIS);
	SELECT FECHAPEDIDO INTO FECHAP FROM PEDIDOS WHERE CODIGOPEDIDO=CP;
	DBMS_OUTPUT.PUT_LINE('FECHA DEL PEDIDO: '||FECHAP);
	-- MOSTRAMOS LAS LÍNEAS DE DETALLE DEL PEDIDO.
	DBMS_OUTPUT.PUT_LINE('*************** DETALLES DEL PEDIDO ***********************');
	FOR RDP IN DP LOOP
		DBMS_OUTPUT.PUT_LINE(RDP.CODIGOPRODUCTO||' -- '||RDP.NOMBRE||' -- '||RDP.CANTIDAD||' Uds x '||
		RDP.PRECIOUNIDAD||' € = '||(RDP.CANTIDAD*RDP.PRECIOUNIDAD)||' €');
	END LOOP;
	SELECT SUM(CANTIDAD*PRECIOUNIDAD) INTO TOTALP FROM DETALLEPEDIDOS WHERE CODIGOPEDIDO=CP;
	DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------');
	DBMS_OUTPUT.PUT_LINE('EL PRECIO DEL PEDIDO ES: '||TOTALP||' €  21% DE IVA: '||(TOTALP*0.21)||'€  TOTAL: '||TOTALP*1.21||' €');
END;
/

